packages = ["rsa"]

[[fetch]]
files = [
    "WebKit/__init__.py", "WebKit/styleMap.json", "WebKit/HTML.py", "WebKit/CSS.py", "WebKit/JS.py", "WebKit/WS.py", "WebKit/Widget.py",
    "index.py",
    "pages/config.json", "pages/home.py", "pages/links.py", "pages/portal.py", "pages/contact.py", "pages/login.py",
    "subs/portal_sonos.py", "subs/portal_tapo.py", "subs/portal_ytdl.py", "subs/portal_sheets.py", "subs/portal_trees.py"
]